[package]
name = "whoisthere"
version = "0.1.1"
authors = ["Sunshine <sunshine@uberspace.net>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
regex = "1.4.5"
whois-rust = "1.2.4"

[dependencies.clap]
version = "2.33.3"
default-features = false
features = [ "suggestions" ]
